### ISSUE TITLE
Output is not uglified, making React bundle twice the size

### ISSUE THREAD

**Issue by gaearon** [GoogleChrome/sample-framework-boot#8]
I haven't had time to check if it causes any significant lag (probably not) but just noticed the results are not uglified. In case of React it actually matters because Uglify will cut out DEV-only code like this:

<img width="516" alt="screen shot 2016-12-30 at 21 11 52" src="https://cloud.githubusercontent.com/assets/810438/21572742/9f798a08-ced4-11e6-971f-4670339bdda5.png">

React has a ton of such checks, and sometimes even when they're known to be `false`, they trigger slow path due to `try`/`catch`es and other slow patterns that would have been eliminated if you used Uglify.

I tried adding Uglify but then noticed you aren't transpiling classes, so Uglify chokes on them. At this point I don't know if it's worth adding class transform to all fixtures or not. But I'd say it's important to leave Uglify enabled because this is how people use React in real world.

**Comment by gaearon** [comment]
You can also just use `react/dist/react.min.js` and `react-dom/dist/react-dom.min.js` directly.
This cuts the bundle size in half (although I don't know how it affects speed).

**Comment by marcello3d** [comment]
@gaearon tried https://github.com/babel/babili ? It can minify es6 (I've been using it successfully with electron/react/redux)

**Comment by gaearon** [comment]
I tried but couldn't figure out how to make it work with Rollup. Adding preset didn't help.

Also now that I think of it this seems like pretty important... if the benchmark includes connection it's awkward the built bundle is twice larger than it should have been. React even specifically provides prebuilt UMD files for cases when you aren't sure how to bundle them.
